### PR TITLE
Fix Restart

### PR DESCRIPTION
**Pull request by NoviProg**

### CODE REVIEW

**Comment by Martin-Molinero** [comment]
Hey @NoviProg! Curious what's the issue you are experiencing, mind sharing some logs and details in a new issue?

**Comment by NoviProg** [comment]
var _lastStartResult not clean 
if i get error i never can't restart IB

**Comment by Martin-Molinero** [comment]
What's the error `_lastStartResult` is set too, logs/deailts? I believe there are some cases where it's expected for the error to be unrecoverable

**Comment by NoviProg** [comment]
Error:
An existing session was detected and will not be automatically disconnected. Please close the existing session manually. (ExistingSessionDetected) (0)

And i have retryes (iterator). i want to try reconnect after delay

example

void Exited(object sender, ExitedEventArgs e)
        {
            var result = p_IBAutomater.GetLastStartResult();
            p_Logger.LogInformation($"IB Gateway close detected: {result.ErrorMessage} ({result.ErrorCode}) ({e.ExitCode})");

            switch (result.ErrorCode)
            {
                case ErrorCode.None:
                case ErrorCode.ProcessStartFailed:
                case ErrorCode.JavaException:
                case ErrorCode.InitializationTimeout:
                    {
                        p_Logger.LogInformation($"Restarting IBAutomater in 10 seconds");
                        await Task.Delay(TimeSpan.FromSeconds(10));
                        result = Restart();
                        break;
                    }
                case ErrorCode.ExistingSessionDetected:
                    {
                        if (!p_ExistingSessionDetectedRetrysMin.IsDone())
                        {
                            int sleepmin = (int)p_ExistingSessionDetectedRetrysMin.Next();
                            p_Logger.LogInformation($"Restarting IBAutomater in {sleepmin} minutes");
                            await Task.Delay(TimeSpan.FromMinutes(sleepmin));
                            result = Restart();
                            if (!result.HasError)
                                p_ExistingSessionDetectedRetrysMin.SetCurrentIndex();
                        }
                        break;
                    }
                case ErrorCode.UnknownMessageWindowDetected:
                case ErrorCode.IbGatewayVersionNotInstalled:
                case ErrorCode.JavaNotFound:
                case ErrorCode.LoginFailed:
                case ErrorCode.SecurityDialogDetected:
                case ErrorCode.TwoFactorConfirmationTimeout:
                case ErrorCode.UnsupportedVersion:
                case ErrorCode.ApiSupportNotAvailable:
                case ErrorCode.RestartedProcessNotFound:
                default:
                    break;
            }

        }

**Comment by Martin-Molinero** [comment]
Hey @NoviProg!
`An existing session was detected and will not be automatically disconnected. Please close the existing session manually.` error type is not recoverable by design at the moment

**Pull request closed without merging**
